blank_issues_enabled: false
contact_links:
  - name: Octopus Energy Italy Community Support
    url: https://github.com/samuelebistoletti/HomeAssistant-OctopusEnergyIT/discussions
    about: Please ask and answer questions here.
