
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  logs:
    custom_components.octopus_energy_it: debug
    custom_components.octopus_energy_it.octopus_energy_it: debug
    custom_components.octopus_energy_it.switch: debug